name: Tags test

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo ${{ github.ref }}
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
